server:
    port: 8080
spring:
logging:
     level:
        org.springframework.messaging: DEBUG

---
spring:
    profiles: prod
logging:
    path: "/opt/log"
    level: INFO

---
spring:
    profiles: digital
    data:
        mongodb:
            host: 138.197.24.195
            port: 27017
            dbname: test
---
spring:
    profiles: docker
    data:
        mongodb:
            host: 172.17.0.1
            port: 27018
            dbname: test
