spring:
    profiles: digital
    data:
        mongodb:
            host: 138.197.24.195
            port: 27017
            dbname: test               
server:
    port: 8080
logging:
    path: "/opt/log"

---
spring:
    profiles: docker
    data:
        mongodb:
            host: 172.17.0.1
            port: 27018
            dbname: test
server:
    port: 8080